osx_image: xcode8
language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/AmazonS3RequestManager.xcworkspace

matrix:
    include:
        - env: SDK=iphonesimulator10.0 SCHEME=iOS          
        - env: SDK=macosx10.12 SCHEME=OSX

script:
- set -o pipefail && xcodebuild test -workspace ./Example/AmazonS3RequestManager.xcworkspace -scheme $SCHEME -sdk $SDK -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty